// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tilebox/v1/ModisFpar.proto

package v1

import (
	reflect "reflect"
	unsafe "unsafe"

	v1 "github.com/tilebox/tilebox-go/protogen/datasets/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModisFpar struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Time                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time"`
	xxx_hidden_Id                   *v1.UUID               `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_IngestionTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ingestion_time,json=ingestionTime"`
	xxx_hidden_Geometry             *v1.Geometry           `protobuf:"bytes,4,opt,name=geometry"`
	xxx_hidden_AssetUrl             *string                `protobuf:"bytes,5,opt,name=asset_url,json=assetUrl"`
	xxx_hidden_Creator              *string                `protobuf:"bytes,6,opt,name=creator"`
	xxx_hidden_ProductVersion       *string                `protobuf:"bytes,7,opt,name=product_version,json=productVersion"`
	xxx_hidden_SensorType           *string                `protobuf:"bytes,8,opt,name=sensor_type,json=sensorType"`
	xxx_hidden_ConsolidationPeriod  *string                `protobuf:"bytes,9,opt,name=consolidation_period,json=consolidationPeriod"`
	xxx_hidden_Days                 int64                  `protobuf:"varint,10,opt,name=days"`
	xxx_hidden_FileCreation         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=file_creation,json=fileCreation"`
	xxx_hidden_Flags                []string               `protobuf:"bytes,12,rep,name=flags"`
	xxx_hidden_LowestActualValue    float64                `protobuf:"fixed64,13,opt,name=lowest_actual_value,json=lowestActualValue"`
	xxx_hidden_HighestActualValue   float64                `protobuf:"fixed64,14,opt,name=highest_actual_value,json=highestActualValue"`
	xxx_hidden_LowestPossibleValue  float64                `protobuf:"fixed64,15,opt,name=lowest_possible_value,json=lowestPossibleValue"`
	xxx_hidden_HighestPossibleValue float64                `protobuf:"fixed64,16,opt,name=highest_possible_value,json=highestPossibleValue"`
	xxx_hidden_Lineage              *string                `protobuf:"bytes,17,opt,name=lineage"`
	xxx_hidden_ProgramVersion       *string                `protobuf:"bytes,18,opt,name=program_version,json=programVersion"`
	xxx_hidden_Width                int64                  `protobuf:"varint,19,opt,name=width"`
	xxx_hidden_Height               int64                  `protobuf:"varint,20,opt,name=height"`
	xxx_hidden_PixelSizeX           float64                `protobuf:"fixed64,21,opt,name=pixel_size_x,json=pixelSizeX"`
	xxx_hidden_PixelSizeY           float64                `protobuf:"fixed64,22,opt,name=pixel_size_y,json=pixelSizeY"`
	xxx_hidden_Crs                  *string                `protobuf:"bytes,23,opt,name=crs"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ModisFpar) Reset() {
	*x = ModisFpar{}
	mi := &file_tilebox_v1_ModisFpar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModisFpar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModisFpar) ProtoMessage() {}

func (x *ModisFpar) ProtoReflect() protoreflect.Message {
	mi := &file_tilebox_v1_ModisFpar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModisFpar) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *ModisFpar) GetId() *v1.UUID {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *ModisFpar) GetIngestionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_IngestionTime
	}
	return nil
}

func (x *ModisFpar) GetGeometry() *v1.Geometry {
	if x != nil {
		return x.xxx_hidden_Geometry
	}
	return nil
}

func (x *ModisFpar) GetAssetUrl() string {
	if x != nil {
		if x.xxx_hidden_AssetUrl != nil {
			return *x.xxx_hidden_AssetUrl
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetCreator() string {
	if x != nil {
		if x.xxx_hidden_Creator != nil {
			return *x.xxx_hidden_Creator
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetProductVersion() string {
	if x != nil {
		if x.xxx_hidden_ProductVersion != nil {
			return *x.xxx_hidden_ProductVersion
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetSensorType() string {
	if x != nil {
		if x.xxx_hidden_SensorType != nil {
			return *x.xxx_hidden_SensorType
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetConsolidationPeriod() string {
	if x != nil {
		if x.xxx_hidden_ConsolidationPeriod != nil {
			return *x.xxx_hidden_ConsolidationPeriod
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetDays() int64 {
	if x != nil {
		return x.xxx_hidden_Days
	}
	return 0
}

func (x *ModisFpar) GetFileCreation() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FileCreation
	}
	return nil
}

func (x *ModisFpar) GetFlags() []string {
	if x != nil {
		return x.xxx_hidden_Flags
	}
	return nil
}

func (x *ModisFpar) GetLowestActualValue() float64 {
	if x != nil {
		return x.xxx_hidden_LowestActualValue
	}
	return 0
}

func (x *ModisFpar) GetHighestActualValue() float64 {
	if x != nil {
		return x.xxx_hidden_HighestActualValue
	}
	return 0
}

func (x *ModisFpar) GetLowestPossibleValue() float64 {
	if x != nil {
		return x.xxx_hidden_LowestPossibleValue
	}
	return 0
}

func (x *ModisFpar) GetHighestPossibleValue() float64 {
	if x != nil {
		return x.xxx_hidden_HighestPossibleValue
	}
	return 0
}

func (x *ModisFpar) GetLineage() string {
	if x != nil {
		if x.xxx_hidden_Lineage != nil {
			return *x.xxx_hidden_Lineage
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetProgramVersion() string {
	if x != nil {
		if x.xxx_hidden_ProgramVersion != nil {
			return *x.xxx_hidden_ProgramVersion
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) GetWidth() int64 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *ModisFpar) GetHeight() int64 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *ModisFpar) GetPixelSizeX() float64 {
	if x != nil {
		return x.xxx_hidden_PixelSizeX
	}
	return 0
}

func (x *ModisFpar) GetPixelSizeY() float64 {
	if x != nil {
		return x.xxx_hidden_PixelSizeY
	}
	return 0
}

func (x *ModisFpar) GetCrs() string {
	if x != nil {
		if x.xxx_hidden_Crs != nil {
			return *x.xxx_hidden_Crs
		}
		return ""
	}
	return ""
}

func (x *ModisFpar) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *ModisFpar) SetId(v *v1.UUID) {
	x.xxx_hidden_Id = v
}

func (x *ModisFpar) SetIngestionTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_IngestionTime = v
}

func (x *ModisFpar) SetGeometry(v *v1.Geometry) {
	x.xxx_hidden_Geometry = v
}

func (x *ModisFpar) SetAssetUrl(v string) {
	x.xxx_hidden_AssetUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 23)
}

func (x *ModisFpar) SetCreator(v string) {
	x.xxx_hidden_Creator = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 23)
}

func (x *ModisFpar) SetProductVersion(v string) {
	x.xxx_hidden_ProductVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 23)
}

func (x *ModisFpar) SetSensorType(v string) {
	x.xxx_hidden_SensorType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 23)
}

func (x *ModisFpar) SetConsolidationPeriod(v string) {
	x.xxx_hidden_ConsolidationPeriod = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 23)
}

func (x *ModisFpar) SetDays(v int64) {
	x.xxx_hidden_Days = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 23)
}

func (x *ModisFpar) SetFileCreation(v *timestamppb.Timestamp) {
	x.xxx_hidden_FileCreation = v
}

func (x *ModisFpar) SetFlags(v []string) {
	x.xxx_hidden_Flags = v
}

func (x *ModisFpar) SetLowestActualValue(v float64) {
	x.xxx_hidden_LowestActualValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 23)
}

func (x *ModisFpar) SetHighestActualValue(v float64) {
	x.xxx_hidden_HighestActualValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 23)
}

func (x *ModisFpar) SetLowestPossibleValue(v float64) {
	x.xxx_hidden_LowestPossibleValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 23)
}

func (x *ModisFpar) SetHighestPossibleValue(v float64) {
	x.xxx_hidden_HighestPossibleValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 23)
}

func (x *ModisFpar) SetLineage(v string) {
	x.xxx_hidden_Lineage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 23)
}

func (x *ModisFpar) SetProgramVersion(v string) {
	x.xxx_hidden_ProgramVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 17, 23)
}

func (x *ModisFpar) SetWidth(v int64) {
	x.xxx_hidden_Width = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 23)
}

func (x *ModisFpar) SetHeight(v int64) {
	x.xxx_hidden_Height = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 23)
}

func (x *ModisFpar) SetPixelSizeX(v float64) {
	x.xxx_hidden_PixelSizeX = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 20, 23)
}

func (x *ModisFpar) SetPixelSizeY(v float64) {
	x.xxx_hidden_PixelSizeY = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 23)
}

func (x *ModisFpar) SetCrs(v string) {
	x.xxx_hidden_Crs = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 22, 23)
}

func (x *ModisFpar) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *ModisFpar) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *ModisFpar) HasIngestionTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IngestionTime != nil
}

func (x *ModisFpar) HasGeometry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Geometry != nil
}

func (x *ModisFpar) HasAssetUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ModisFpar) HasCreator() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ModisFpar) HasProductVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ModisFpar) HasSensorType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ModisFpar) HasConsolidationPeriod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ModisFpar) HasDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ModisFpar) HasFileCreation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FileCreation != nil
}

func (x *ModisFpar) HasLowestActualValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ModisFpar) HasHighestActualValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *ModisFpar) HasLowestPossibleValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *ModisFpar) HasHighestPossibleValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *ModisFpar) HasLineage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *ModisFpar) HasProgramVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 17)
}

func (x *ModisFpar) HasWidth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *ModisFpar) HasHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *ModisFpar) HasPixelSizeX() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 20)
}

func (x *ModisFpar) HasPixelSizeY() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *ModisFpar) HasCrs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 22)
}

func (x *ModisFpar) ClearTime() {
	x.xxx_hidden_Time = nil
}

func (x *ModisFpar) ClearId() {
	x.xxx_hidden_Id = nil
}

func (x *ModisFpar) ClearIngestionTime() {
	x.xxx_hidden_IngestionTime = nil
}

func (x *ModisFpar) ClearGeometry() {
	x.xxx_hidden_Geometry = nil
}

func (x *ModisFpar) ClearAssetUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_AssetUrl = nil
}

func (x *ModisFpar) ClearCreator() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Creator = nil
}

func (x *ModisFpar) ClearProductVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ProductVersion = nil
}

func (x *ModisFpar) ClearSensorType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SensorType = nil
}

func (x *ModisFpar) ClearConsolidationPeriod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ConsolidationPeriod = nil
}

func (x *ModisFpar) ClearDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Days = 0
}

func (x *ModisFpar) ClearFileCreation() {
	x.xxx_hidden_FileCreation = nil
}

func (x *ModisFpar) ClearLowestActualValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_LowestActualValue = 0
}

func (x *ModisFpar) ClearHighestActualValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_HighestActualValue = 0
}

func (x *ModisFpar) ClearLowestPossibleValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_LowestPossibleValue = 0
}

func (x *ModisFpar) ClearHighestPossibleValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_HighestPossibleValue = 0
}

func (x *ModisFpar) ClearLineage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_Lineage = nil
}

func (x *ModisFpar) ClearProgramVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 17)
	x.xxx_hidden_ProgramVersion = nil
}

func (x *ModisFpar) ClearWidth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_Width = 0
}

func (x *ModisFpar) ClearHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_Height = 0
}

func (x *ModisFpar) ClearPixelSizeX() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 20)
	x.xxx_hidden_PixelSizeX = 0
}

func (x *ModisFpar) ClearPixelSizeY() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_PixelSizeY = 0
}

func (x *ModisFpar) ClearCrs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 22)
	x.xxx_hidden_Crs = nil
}

type ModisFpar_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Time                 *timestamppb.Timestamp
	Id                   *v1.UUID
	IngestionTime        *timestamppb.Timestamp
	Geometry             *v1.Geometry
	AssetUrl             *string
	Creator              *string
	ProductVersion       *string
	SensorType           *string
	ConsolidationPeriod  *string
	Days                 *int64
	FileCreation         *timestamppb.Timestamp
	Flags                []string
	LowestActualValue    *float64
	HighestActualValue   *float64
	LowestPossibleValue  *float64
	HighestPossibleValue *float64
	Lineage              *string
	ProgramVersion       *string
	Width                *int64
	Height               *int64
	PixelSizeX           *float64
	PixelSizeY           *float64
	Crs                  *string
}

func (b0 ModisFpar_builder) Build() *ModisFpar {
	m0 := &ModisFpar{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_IngestionTime = b.IngestionTime
	x.xxx_hidden_Geometry = b.Geometry
	if b.AssetUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 23)
		x.xxx_hidden_AssetUrl = b.AssetUrl
	}
	if b.Creator != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 23)
		x.xxx_hidden_Creator = b.Creator
	}
	if b.ProductVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 23)
		x.xxx_hidden_ProductVersion = b.ProductVersion
	}
	if b.SensorType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 23)
		x.xxx_hidden_SensorType = b.SensorType
	}
	if b.ConsolidationPeriod != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 23)
		x.xxx_hidden_ConsolidationPeriod = b.ConsolidationPeriod
	}
	if b.Days != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 23)
		x.xxx_hidden_Days = *b.Days
	}
	x.xxx_hidden_FileCreation = b.FileCreation
	x.xxx_hidden_Flags = b.Flags
	if b.LowestActualValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 23)
		x.xxx_hidden_LowestActualValue = *b.LowestActualValue
	}
	if b.HighestActualValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 23)
		x.xxx_hidden_HighestActualValue = *b.HighestActualValue
	}
	if b.LowestPossibleValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 23)
		x.xxx_hidden_LowestPossibleValue = *b.LowestPossibleValue
	}
	if b.HighestPossibleValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 23)
		x.xxx_hidden_HighestPossibleValue = *b.HighestPossibleValue
	}
	if b.Lineage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 23)
		x.xxx_hidden_Lineage = b.Lineage
	}
	if b.ProgramVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 17, 23)
		x.xxx_hidden_ProgramVersion = b.ProgramVersion
	}
	if b.Width != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 23)
		x.xxx_hidden_Width = *b.Width
	}
	if b.Height != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 23)
		x.xxx_hidden_Height = *b.Height
	}
	if b.PixelSizeX != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 20, 23)
		x.xxx_hidden_PixelSizeX = *b.PixelSizeX
	}
	if b.PixelSizeY != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 23)
		x.xxx_hidden_PixelSizeY = *b.PixelSizeY
	}
	if b.Crs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 22, 23)
		x.xxx_hidden_Crs = b.Crs
	}
	return m0
}

var File_tilebox_v1_ModisFpar_proto protoreflect.FileDescriptor

const file_tilebox_v1_ModisFpar_proto_rawDesc = "" +
	"\n" +
	"\x1atilebox/v1/ModisFpar.proto\x12\n" +
	"tilebox.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"datasets/v1/well_known_types.proto\"\x86\a\n" +
	"\tModisFpar\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12!\n" +
	"\x02id\x18\x02 \x01(\v2\x11.datasets.v1.UUIDR\x02id\x12A\n" +
	"\x0eingestion_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ringestionTime\x121\n" +
	"\bgeometry\x18\x04 \x01(\v2\x15.datasets.v1.GeometryR\bgeometry\x12\x1b\n" +
	"\tasset_url\x18\x05 \x01(\tR\bassetUrl\x12\x18\n" +
	"\acreator\x18\x06 \x01(\tR\acreator\x12'\n" +
	"\x0fproduct_version\x18\a \x01(\tR\x0eproductVersion\x12\x1f\n" +
	"\vsensor_type\x18\b \x01(\tR\n" +
	"sensorType\x121\n" +
	"\x14consolidation_period\x18\t \x01(\tR\x13consolidationPeriod\x12\x12\n" +
	"\x04days\x18\n" +
	" \x01(\x03R\x04days\x12?\n" +
	"\rfile_creation\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ffileCreation\x12\x14\n" +
	"\x05flags\x18\f \x03(\tR\x05flags\x12.\n" +
	"\x13lowest_actual_value\x18\r \x01(\x01R\x11lowestActualValue\x120\n" +
	"\x14highest_actual_value\x18\x0e \x01(\x01R\x12highestActualValue\x122\n" +
	"\x15lowest_possible_value\x18\x0f \x01(\x01R\x13lowestPossibleValue\x124\n" +
	"\x16highest_possible_value\x18\x10 \x01(\x01R\x14highestPossibleValue\x12\x18\n" +
	"\alineage\x18\x11 \x01(\tR\alineage\x12'\n" +
	"\x0fprogram_version\x18\x12 \x01(\tR\x0eprogramVersion\x12\x14\n" +
	"\x05width\x18\x13 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\x14 \x01(\x03R\x06height\x12 \n" +
	"\fpixel_size_x\x18\x15 \x01(\x01R\n" +
	"pixelSizeX\x12 \n" +
	"\fpixel_size_y\x18\x16 \x01(\x01R\n" +
	"pixelSizeY\x12\x10\n" +
	"\x03crs\x18\x17 \x01(\tR\x03crsB\fZ\n" +
	"tilebox/v1b\beditionsp\xe8\a"

var file_tilebox_v1_ModisFpar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tilebox_v1_ModisFpar_proto_goTypes = []any{
	(*ModisFpar)(nil),             // 0: tilebox.v1.ModisFpar
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*v1.UUID)(nil),               // 2: datasets.v1.UUID
	(*v1.Geometry)(nil),           // 3: datasets.v1.Geometry
}
var file_tilebox_v1_ModisFpar_proto_depIdxs = []int32{
	1, // 0: tilebox.v1.ModisFpar.time:type_name -> google.protobuf.Timestamp
	2, // 1: tilebox.v1.ModisFpar.id:type_name -> datasets.v1.UUID
	1, // 2: tilebox.v1.ModisFpar.ingestion_time:type_name -> google.protobuf.Timestamp
	3, // 3: tilebox.v1.ModisFpar.geometry:type_name -> datasets.v1.Geometry
	1, // 4: tilebox.v1.ModisFpar.file_creation:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tilebox_v1_ModisFpar_proto_init() }
func file_tilebox_v1_ModisFpar_proto_init() {
	if File_tilebox_v1_ModisFpar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilebox_v1_ModisFpar_proto_rawDesc), len(file_tilebox_v1_ModisFpar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilebox_v1_ModisFpar_proto_goTypes,
		DependencyIndexes: file_tilebox_v1_ModisFpar_proto_depIdxs,
		MessageInfos:      file_tilebox_v1_ModisFpar_proto_msgTypes,
	}.Build()
	File_tilebox_v1_ModisFpar_proto = out.File
	file_tilebox_v1_ModisFpar_proto_goTypes = nil
	file_tilebox_v1_ModisFpar_proto_depIdxs = nil
}
